using script reflection

options:
	rubishineDescription: "A blade shining with red jewels, given only to the strongest."
	gildedgreatswordDescription: "A heavy blade coated in gold, capable of dealing the heaviest of blows."
	shimmerfangDescription: "A narrow blade glistening in the moonlight. Agile and precise, this rapier uses fast thrust attacks."
	bladerenderDescription: "A scythe gleaming with metal fragments, boasting a wide sweeping radius."
	earthshakerDescription: "A heavy axe made to fell the earth. Final attacks emit shockwaves, dealing heavy knockback."
	hellbentdaggerDescription: "A twisted knife, burning from the base of the blade. Final attacks ignite targets for additional damage."
	crossbladeDescription: "A unique spear with a three-pronged blade, capable of being used for both thrust and slash attacks."
	dragonboltDescription: "A scale ripped from the body of a dragon. Electricity still flows through its blade, even to this day."
	onimaruDescription: "A pair of twin katanas, able to be wielded in tandem. Slashes are able to double-hit enemies."
	chainbladeDescription: "A segmented blade of interlocking razors, extending reach with each swing for deadly follow-ups."


	resonanceDescription: "A bow whose strings echo throughout the very world itself. Capable of both close ranged swipes and mid-range attacks."
	frostfallDescription: "A frozen staff, encased in a block of ice. Capable of slowing and pummelling opponents."
	arcanumDescription: "A magic wand, imbued with the power to wield powerful crystals. Deals great knockback."
	ashfireDescription: "A shortbow formed of the ashes from a burning village, lost in time. Creates blazing infernos, burning all who touch it."
	bonebladeDescription: "A poisonous bone rended from the corpse of a snake. The venom held within the tip of the blade remains potent."
	bloodthornDescription: "A blood-soaked rose, coated in barbs. Deals damage to the user in order to harm foes."




	moonveilDescription: "Katana forged of glintstone. Masterpiece of a Sellian swordsmith. Light enwreathes the blade when sheathed, explaining its Moonveil moniker."

	


# <##ff2458>🗡
# <##2eadd7>★


on load:
	
	clear {-movesets::*}
	set {-movesets::standard::hits} to 3
	set {-movesets::heavy::hits} to 4
	set {-movesets::light::hits} to 2

	clear {-weapontypes::*}
	set {-weapontypes::primary} to "&8ᴘʀɪᴍᴀʀʏ ᴡᴇᴀᴘᴏɴ"
	set {-weapontypes::secondary} to "&8sᴇᴄᴏɴᴅᴀʀʏ ᴡᴇᴀᴘᴏɴ"
	set {-weapontypes::armour} to "&8ᴀʀᴍᴏᴜʀ"
	set {-weapontypes::suffix} to "&8sᴜғғɪx"
	clear {-weapons::*}
    
	set {momentum-offset} to 1.5

	registerWeapon("&c&lRubishine", {@rubishineDescription}, iron sword, "primary", "standard", "A basic combo of three slash attacks.", 0, ("quickstep", "parry", "unsheathe", "thrust", "rippleblade", "hook"), (1, 1.125, 1.25), ((9 ticks), (10 ticks) and (13 ticks))) # 8, 8, 10
	registerWeapon("<##FCDB47>&lGilded Greatsword", {@gildedgreatswordDescription}, golden sword, "primary", "heavy", "A heavy combo of four slow slashes.", 0, ("quickstep", "parry", "unsheathe", "thrust", "flame dance", "eruption", "vortex"), (1.1, 1.25, 1.15, 1.3), ((14 ticks), (13 ticks), (16 ticks), (14 ticks)))
	registerWeapon("<##3BD7EE>&lShimmerfang", {@shimmerfangDescription}, diamond sword, "primary", "light", "A quick combo of two light jabs.", 0, ("quickstep", "parry", "unsheathe", "thrust", "rippleblade", "thunderbolt", "escape"), (1, 1.125), ((8 ticks), (11 ticks)))
	registerWeapon("<##7D53FF>&lBladerender", {@bladerenderDescription}, netherite hoe, "primary", "standard", "A combo of three reaping attacks. Pulls targets towards you.", 3000, ("quickstep", "parry", "shroud", "rippleblade", "hook", "vortex"), (1.125, 1, 1.25), ((13 ticks), (15 ticks), (19 ticks)))
	registerWeapon("<##43F53E>&lEarthshaker", {@earthshakerDescription}, iron axe, "primary", "heavy", "A slower combo of four axe strikes.", 3000, ("quickstep", "parry", "flame dance", "hook", "vortex", "eruption"), (1.125, 1.25, 1.375, 1.25), ((12 ticks), (13 ticks), (14 ticks), (20 ticks)))
	registerWeapon("<##FF6D3F>&lHellbent Dagger", {@hellbentdaggerDescription}, stone sword, "primary", "light", "A rapid combo of four fast slashes.", 3000, ("quickstep", "parry", "flame dance", "hook", "shroud", "eruption"), (1, 1.125, 1.15, 1.1), ((7 ticks), (7 ticks), (8 ticks), (8 ticks)))
	registerWeapon("<##E2644E>&lCrossblade", {@crossbladeDescription}, iron pickaxe, "primary", "heavy", "A medium range combo of thrusts and slashes.", 4000, ("parry", "thrust", "rippleblade", "vortex", "thunderbolt", "blitz"), (1.2, 1.25, 1.3, 1.5), ((17 ticks), (15 ticks), (17 ticks), (19 ticks)))
	registerWeapon("<##5BC0BE>&lOnimaru", {@onimaruDescription}, netherite sword, "primary", "light", "A combo of dual swipes and slashes.", 4000, ("quickstep", "parry", "unsheathe", "thrust", "thunderbolt", "hook"), (0.65, 0.75, 0.85), ((10 tick), (8 tick), (9 tick)), (0))
	registerWeapon("<#556577>&lChainblade", {@chainbladeDescription}, iron hoe, "primary", "standard", "A combo of swipes and extending slashes.", 4000, ("quickstep", "parry", "unsheathe", "flame dance", "rippleblade", "hook"), (1, 1.1, 1.1, 1.2), ((13 ticks), (14 ticks), (16 ticks), (14 ticks)), (0), (""))

	registerWeapon("<##3FFFB9>&lResonance", {@resonanceDescription}, bow, "secondary", "standard", "A traditional combo of three medium damage attacks.", 0, ("escape", "hook", "reinforce", "blitz", "shroud"), (1, 0.75, 1.25), ((14 ticks), (20 ticks), (30 ticks)), (3, 5, 5), ("<##3FFFB9>&lSwipe", "<##3FFFB9>&lMagic Bolt", "<##3FFFB9>&lArcane Bolt"))
	registerWeapon("<##9A3FFF>&lArcanum", {@arcanumDescription}, stick, "secondary", "heavy", "A slower combo of two close range attacks.", 2000, ("escape", "hook", "reinforce", "blitz", "shroud"), (1, 1.25), ((40 ticks), (50 ticks)), (5, 5), ("<##9A3FFF>&lCrystal Release", "<##9A3FFF>&lShatter"))
	registerWeapon("<##70EDFC>&lFrostfall", {@frostfallDescription}, iron shovel, "secondary", "heavy", "A slow combo of three freezing attacks.", 3000, ("escape", "hook", "reinforce", "blitz", "shroud"), (1.25, 0.4, 0.75), ((50 ticks), (65 ticks), (80 ticks)), (4, 5, 6), ("<##70EDFC>&lDeepfreeze", "<##70EDFC>&lBlizzard", "<##70EDFC>&lIce Snake"))
	registerWeapon("<##FF6253>&lAshfire", {@ashfireDescription}, bow, "secondary", "light", "A fast combo of arrows and area-denial attacks.", 2000, ("quickstep", "parry", "hook", "escape", "shroud"), (0.6, 1, 1.25), ((40 ticks), (60 ticks), (50 ticks)), (4, 5, 5), ("<##FF6253>&lFire Bolt", "<##FF6253>&lRain of Fire", "<##FF6253>&lMagma Wall"))
	set {_bone-blade} to tipped arrow
	set int tag "minecraft:potion_contents;custom_color" of nbt of {_bone-blade} to 5620757
	registerWeapon("<##73EE2C>&lBone Blade", {@bonebladeDescription}, {_bone-blade}, "secondary", "light", "A quick combo of two melee and ranged attacks.", 3000, ("parry", "shroud", "hook", "blitz"), (0.6, 0.8), ((16 ticks), (20 ticks)), (4, 4), ("<##73EE2C>&lBone Swipe", "<##73EE2C>&lVenomous Fang"))
	registerWeapon("<##CD0A1B>&lBloodthorn", {@bloodthornDescription}, poppy, "secondary", "standard", "A combo of three self-harming attacks.", 3000, ("hook", "shroud", "escape", "blitz"), (1.2, 1.2, 1.35), ((16 ticks), (18 ticks), (20 ticks)), (3, 4, 4), ("<##CD0A1B>&lBloodied Barbs", "<##CD0A1B>&lImpenetrable Thorns", "<##CD0A1B>&lHidden Roots"))




	#registerWeapon("<##A4E5FF>&lMoonveil", {@moonveilDescription}, netherite sword, "primary", "standard", "A combo of five slash attacks.", 0, ("quickstep", "parry", "transient moonlight", "hook"), (1, 1.1, 1.15, 1.2, 1.3), ((7 tick), (8 tick), (9 tick), (10 tick), (12 tick)), (0), (""), true)
	#registerWeapon("<##FFF700>&lDragonbolt", {@dragonboltDescription}, golden shovel, "primary", "standard", "A combo of jabs and slashes, having both range and sweep attacks.", 4000, ("quickstep", "hook", "thrust", "thunderbolt", "blitz"), (1, 1.1, 1.2), ((10 ticks), (12 ticks), (15 ticks)))

	# used for dungeon cd stuff
	set {-weapon-items::primary::*} to stone sword, iron sword, golden sword, diamond sword, iron axe, iron pickaxe, iron hoe, netherite sword, netherite hoe
	set {-weapon-items::secondary::*} to iron shovel, stick, bow, poppy, tipped arrow

	# set combo reset timer
	loop indices of {-weapons::*}:
		clear {_avg}
		loop {-weapons::%loop-value%::cooldown::*}:
			add loop-value-2 to {_avg}
		set {_avg} to 1.5 * (ticks of ({_avg} / (size of {-weapons::%loop-value%::cooldown::*})))
		set {_clamped} to first element out of clamp({_avg}, 35, 100)
		set {-weapons::%loop-value%::combo-timer} to "%{_clamped}% ticks" parsed as timespan
	

	# hardcode rahhh
	set {-weapons::resonance::combo-timer} to 2.5 seconds
	set {-weapons::frostfall::combo-timer} to 6 seconds
	set {-weapons::bloodthorn::combo-timer} to 3 seconds


	loop indices of {-weapons::*}:
		set {-weapon::%loop-value%::cached-item} to getWeapon(loop-value, "hidden")



function registerWeapon(name: text, desc: text, item: item, type: text, moveset: text, moveset-desc: text, cost: integer=0, attunements: strings, damage: numbers, cooldown: timespans, mana: numbers=(0), move-names: strings="", hidden: boolean=false):
	set {_index} to uncolored {_name} in lowercase

	set {-weapons::%{_index}%::name} to {_name}
	set {-weapons::%{_index}%::desc} to {_desc}
	set {-weapons::%{_index}%::item} to {_item}
	set {-weapons::%{_index}%::moveset} to {_moveset}
	set {-weapons::%{_index}%::moveset-desc} to {_moveset-desc}
	set {-weapons::%{_index}%::type} to {_type}
	set {-weapons::%{_index}%::cost} to {_cost}
	set {-weapons::%{_index}%::attunements::*} to {_attunements::*}
	if {_move-names::*} != "":
		set {-weapons::%{_index}%::name::*} to {_move-names::*}
	set {-weapons::%{_index}%::hidden} to true if {_hidden} is true
	if {_type} = "primary":
		set {-weapons::%{_index}%::type-format} to "&8[&c🗡&8]"
	else if {_type} = "secondary":
		set {-weapons::%{_index}%::type-format} to "&8[&a🏹&8]"
	else:
		set {-weapons::%{_index}%::type-format} to "&8[&7◆&8]"
	
	set {-weapons::%{_index}%::damage::*} to {_damage::*}
	set {-weapons::%{_index}%::cooldown::*} to {_cooldown::*}
	loop {_mana::*}:
		loop-value != 0
		set {-weapons::%{_index}%::mana::%loop-counter%} to loop-value
	

	loop (indices of {-weapons::*}) where [{-weapons::%input%::moveset} = {_moveset}]:
		{-weapons::%loop-value%::type} = {_type}
		set {_entry::%loop-counter%} to {-weapons::%loop-value%::order} ? 0
	set {-weapons::%{_index}%::order} to max({_entry::*})+1
	# add hidden


command /getweapon <string>:
	permission: op
	trigger:
		give player getWeapon(arg-1, "none", player)
		play sound "entity.experience_orb.pickup" to player

function getWeapon(index: text, attunement: text="None", p: player={_}) returns item:
	set {_index} to uncolored {_index} in lowercase
	set {_item} to {-weapons::%{_index}%::item}
	set {_name} to {-weapons::%{_index}%::name}
	set {_desc::*} to formatParagraph({-weapons::%{_index}%::desc})
	set {_type} to {-weapontypes::%{-weapons::%{_index}%::type}%}
	set {_type-format} to {-weapons::%{_index}%::type-format}
	set {_moveset} to "&f&n%{-weapons::%{_index}%::moveset} in strict proper case%"
	set {_moveset-desc::*} to formatParagraph({-weapons::%{_index}%::moveset-desc})

	# item model
	if {_p} is set:
		set {_model} to getWeaponColour({_p}, {_index})
	else:
		set {_model} to {_index}
	replace all "onimaru" in {_model} with "onimaru_main"
	replace all " " in {_model} with "_"
	set item model of {_item} to {_model}

	# weapon dmg/mana
	set {_dmg::*} to {-weapons::%{_index}%::damage::*}
	set {_mana::*} to {-weapons::%{_index}%::mana::*}
	loop {_dmg::*}:
		set {_dmg::%loop-counter%} to "&8[&f%loop-value%<##ff2458>🗡&8]"
	set {_dmg} to join {_dmg::*} with " &7⏵ "
	loop {_mana::*}:
		set {_mana::%loop-counter%} to "&8[&f%loop-value%<##2eadd7>★&8]"
	set {_mana} to (join {_mana::*} with " &7⏵ ")
	set {_dmg-mana::*} to {_dmg} and {_mana}

	# attunement dmg/mana
	if ("None" and "hidden") doesn't contain {_attunement}:
		set {_dmg} to {-attunements::%{_attunement}%::damage::%{_index}%} ? {-attunements::%{_attunement}%::damage::1}
		set {_mana} to {-attunements::%{_attunement}%::mana::%{_index}%} ? {-attunements::%{_attunement}%::mana::1}
		if {_dmg} > 0:
			set {_dmg} to "&f%{_dmg}%<##ff2458>🗡"
		if {_mana} is set:
			set {_mana} to "&f%{_mana}%<##2eadd7>★"
		set {_attunement-dmg-mana} to join {_dmg} and {_mana} with " "
		set {_attunement-dmg-mana} to "&8[%{_attunement-dmg-mana}%&8]"

		#loop {_dmg::*}:
		#	set {_dmg::%loop-counter%} to "&8[&f%loop-value%<##ff2458>🗡&8]"
		#set {_dmg} to join {_dmg::*} with " &7⏵ "
		#loop {_mana::*}:
		#	set {_mana::%loop-counter%} to "&8[&f%loop-value%<##2eadd7>★&8]"
		#set {_mana} to (join {_mana::*} with " &7⏵ ")
		#set {_attunement-dmg-mana::*} to {_dmg} and {_mana}
	


	if {_attunement} = "None":
		set {_attunement-desc::*} to formatParagraph("Attune your weapon at the &fAttunement &fMaster &7to add an additional power!")
	else if {_attunement} = "hidden":
		set {_i} to {_item} named "%{_name}% %{_type-format}%" with lore {_type}, "", {_desc::*}, "", "<##2EADD7>&lMOVESET: %{_moveset}%&r", "", {_moveset-desc::*}, "", {_dmg-mana::*} and  "" with all item flags
		
		modify custom nbt of {_i}:
			set string tag "attunement" of nbt to {_attunement}
			set byte tag "weapon" of nbt to 1
			set byte tag "%{-weapons::%{_index}%::type}%" of nbt to 1

			if {_index} = "onimaru":
				set string tag "model-suffix" of nbt to "_main"

			# missing some nbt tags...
		return unbreakable {_i}
		
	else:
		set {_attunement-desc::*} to formatParagraph({-attunements::%uncolored {_attunement} in lowercase%::desc})

	set {_i} to {_item} named "%{_name}% %{_type-format}%" with lore {_type}, "", {_desc::*}, "", "<##2EADD7>&lMOVESET: %{_moveset}%", "", {_moveset-desc::*}, "", {_dmg-mana::*}, "", "", "<##FF9B24>&lATTUNEMENT: &f&n%{_attunement} in strict proper case%", "", {_attunement-desc::*}, "", {_attunement-dmg-mana} and "" with all item flags
	add nbt compound from "{""minecraft:attribute_modifiers"":[{amount:0.0d,display:{type:""hidden""},id:""minecraft:attack_speed"",operation:""add_value"",type:""minecraft:attack_speed""}]}" to nbt of {_i}

	modify custom nbt of {_i}:
		set string tag "attunement" of nbt to {_attunement}
		set byte tag "weapon" of nbt to 1
		set byte tag "%{-weapons::%{_index}%::type}%" of nbt to 1
		set string tag "moveset" of nbt to {-weapons::%{_index}%::moveset}
		set int tag "hits" of nbt to (size of {-weapons::%{_index}%::cooldown::*})
		set string tag "name" of nbt to {_index}

		if {_index} = "onimaru":
			set string tag "model-suffix" of nbt to "_main"

	return unbreakable {_i}





function useAbility(p: player, weapon: text, attunement: text=""):
	{_p}'s gamemode != spectator
	{-tempdata::%uuid of {_p}%::stunned} != true

	set {_cd} to metadata "ability_%{_weapon}%" of {_p}
	set {_cd} to 1 second ago if {_cd} is not set
	set {_hit} to {_p}'s metadata "hit_%{_weapon}%" + 1
	set {_hit} to 1 if {_hit} is not set

	set {_blitzMod} to 0.75 if {-tempdata::%uuid of {_p}%::blitz} = true, else 1
	if {-tempdata::%uuid of {_p}%::boon} = "bestial boon":
		remove 0.25 from {_blitzMod}
		#broadcast "reduce! %{_blitzMod}%"

	set {_old-hit} to mod({_hit}-2, {-movesets::%{-weapons::%{_weapon}%::moveset}%::hits})+1
	set {_old-hit-cd} to "%(ticks of {-weapons::%{_weapon}%::cooldown::%{_old-hit}%}) * 0.6 * {_blitzMod}% ticks" parsed as timespan
	set {_curr-cd} to "%(ticks of item cooldown of {_p}'s tool for {_p})% ticks" parsed as timespan # doesn't need blitzMod, since blitz cd is already applied
    
	#if {_p} is online:
	#	set {_curr-cd} to item cooldown of {_p}'s tool for {_p}
	#else:
	#	set {_curr-cd} to 0 seconds

	#if "%{_p}%" = "Sh_iki":
	#	send "old-hit-cd &8> &e%{_old-hit-cd}%" to {_p}
	#	send "curr-hit-cd &8> &e%{_curr-cd}%" to {_p}


	if {_curr-cd} = 0 seconds:
		# timed
		set {_atk-cooldown} to 1
	else if {_curr-cd} < {_old-hit-cd}:
		# attack
		# 	only goes through if its like 50% done with the cooldown
		set {_curr-cd} to ticks of (difference between {_p}'s metadata "ability_%{_weapon}%" and now)
		set {_move-cd} to 20 + ((ticks of {-weapons::%{_weapon}%::cooldown::%{_old-hit}%} ? {-weapons::%{_weapon}%::cooldown::1}) * {_blitzMod})
		set {_atk-cooldown} to (1 - ({_curr-cd} / {_move-cd}))
		set {_atk-cooldown} to first element out of clamp({_atk-cooldown}, 0, 1) # sometimes it goes negative, idk man
		# atk cooldown * damage = damage dealt
	else:
		# spam clicking too fast
		# 	eats inputs
        
		#broadcast "Too fast | %{_curr-cd}%, %{_old-hit-cd}%"
        
		stop
	

	# reg weapon
	if {_attunement} = "":
		set {_cd-actual} to ({-weapons::%{_weapon}%::cooldown::%{_hit}%})
		set {_moveset-hits} to int tag "hits" of custom nbt of ({_p}'s tool ? getWeapon({_weapon})) # area for potential lag if they're not holding it; uncommon
	# attunement
	else:
		set {_cd-actual} to ({-attunements::%{_attunement}%::cooldown::%{_weapon}%} ? {-attunements::%{_attunement}%::cooldown::%{_hit}%} ? {-attunements::%{_attunement}%::cooldown::1})
		set {_moveset-hits} to size of {-attunements::%{_attunement}%::cooldown::*}


	{_cd-actual} is set
	if {-tempdata::%uuid of {_p}%::blitz} = true:
		set {_cd-actual} to "%(ticks of {_cd-actual}) * {_blitzMod}% ticks" parsed as timespan ? 10 seconds


	# START COOLDOWNS / USE MANA / SET ATTACK SPEED
	useMana({_p}, {_weapon}, {_hit}, {_attunement}, true) = true
	if {_attunement} = "":
		set {_p}'s metadata "ability_%{_weapon}%" to {_cd-actual} from now
		set {_p}'s metadata "hit_%{_weapon}%" to mod({_hit}, {_moveset-hits}+1)
	else:
		set {_p}'s metadata "ability_%{_weapon}%" to {_cd-actual} from now
		set {_p}'s metadata "ability_%{_attunement}%" to {_cd-actual} from now
		set {_p}'s metadata "hit_%{_attunement}%" to mod({_hit}, {_moveset-hits}+1)

	#set item cooldown of {-weapons::%{_weapon}%::item} for {_p} to {_cd-actual}
	set {_type} to {-weapons::%{_weapon}%::type}
	set item cooldown of {-weapon-items::%{_type}%::*} for {_p} to {_cd-actual}
	set {_atk-speed} to 20 / (ticks of {_cd-actual})
	set {_p}'s attack speed attribute to {_atk-speed}

	{_atk-cooldown} != 1:
		set {_atk-cooldown} to {_atk-cooldown} * 0.6 # tryna reduce spam clicking
	

	if {-tempdata::%uuid of {_p}%::boon} = "boon of the desperate":
		make {_p} damage {_p} by (getDamage({_p}, {_weapon}, {_hit}) * {_atk-cooldown}) / 4
		# heaing is in game.sk's `on damage:`


	# CAST ATTUNEMENT
	if {_attunement} != "":

		set {_n} to {_attunement}
		replace all " " in {_n} with ""
		set {_func} to function "%{_n}%Action"
		run {_func} with arguments {_p}, {_weapon}, {_atk-cooldown}

		actionbar({_p})


	# USE WEAPON
	else:
		
		set {_n} to {_weapon}
		replace all " " in {_n} with ""
		set {_func} to function "%{_n}%Action"
		run {_func} with arguments {_p}, {_hit}, {_atk-cooldown}
			
		actionbar({_p})

		# COMBOS
		# 	shows final hit on actionbar for a brief moment
		wait 4 tick
		if {_p}'s metadata "hit_%{_weapon}%" >= {_moveset-hits}:
			loop {_moveset-hits} times:
				{-tempdata::%uuid of {_p}%::combo::%loop-counter%} != true:
					set {_perfect} to false
					exit loop
				else:
					set {_perfect} to true
			if {_perfect} = true:
            
				if {-tempdata::%uuid of {_p}%::tutorial} = 7:
					updateTutorial({_p}, "combos_finish")
            
				if regions at {_p} doesn't contain region "spawn" in world "runeblade": # training dummy prevention
					progressChallenge({_p}, "combo", 1)

			resetCombo({_p}, {_weapon})
			stop

		#	timeout
		set {_delay} to {-weapons::%{_weapon}%::combo-timer} # 60 ticks
		wait {_delay}
		{_p}'s metadata "hit_%{_weapon}%" != 0


		set {_attunement} to string tag "attunement" of custom nbt of {_p}'s tool if {_attunement} = ""
		set {_last-used} to {_cd-actual} before {_p}'s metadata "ability_%{_weapon}%"
		set {_last-used-attunement} to {_cd-actual} before {_p}'s metadata "ability_%{_attunement}%"

		if any:
			difference between {_last-used} and now >= {_delay}
			{_last-used} = {_last-used-attunement}
		then:
			resetCombo({_p}, {_weapon}, true)


	


function hitCombo(p: entity, hit: integer, atk-scale: number, weapon: text, attunement: text=""):
	stop if {_p} is not a player # callable w/ cluster.sk mobs

	if {_atk-scale} = 1:
		set {-tempdata::%uuid of {_p}%::combo::%{_hit}%} to true
	else:
		set {-tempdata::%uuid of {_p}%::combo::%{_hit}%} to false
	actionbar({_p})

	replace all "_" in {_weapon} with " "
	set {_weapon} to {-weapons::%{_weapon}%::name}
	set {_attunement} to "&e&n%{-attunements::%{_attunement}%::name}%" if {-attunements::%{_attunement}%::name} is set
	set {-tempdata::%uuid of {_p}%::last-used} to join {_weapon} and {_attunement} with " &8| "


function resetCombo(p: player, weapon: text, sound: boolean=false):
	set {_p}'s metadata "hit_%{_weapon}%" to 0
	clear {-tempdata::%uuid of {_p}%::combo::*}
	play sound "block.note_block.hat" at volume 10 at pitch 1.5 to {_p} if {_sound} = true
	actionbar({_p})


function useMana(p: player, weapon: text, hit: integer, attunement: text="", sound: boolean=false) returns boolean:
	set {_mana} to {_p}'s metadata "mana"
	if {_attunement} = "":
		set {_cost} to {-weapons::%{_weapon}%::mana::%{_hit}%} ? {-weapons::%{_weapon}%::mana::1} ? 0
		set {_display} to {-weapons::%{_weapon}%::name::%{_hit}%} ? {-weapons::%{_weapon}%::name}
	else:
		set {_cost} to {-attunements::%{_attunement}%::mana::%{_weapon}%} ? {-attunements::%{_attunement}%::mana::1} ? 0
		set {_display} to "&e&n%{-attunements::%{_attunement}%::name}%"

	if {_cost} = 0:
		return true
		
	else if {_mana} >= {_cost}:
		remove {_cost} from {_mana}
		set {_p}'s metadata "mana" to {_mana}
		prioritybar({_p}, "&8«   &7Used %{_display}%&7! &8(<##2eadd7>%{_cost}%★&8)   &8»", 15 tick)
		return true
	
	else:
		if {_sound} = true:
			play sound "block.note_block.bass" at pitch 0.5 to {_p}
			prioritybar({_p}, "&8«   <##2eadd7>&lNOT ENOUGH MANA <##2eadd7>★   &8»", 1 second)
		return false




on arm swing:
	event isn't cancelled
	byte tag "weapon" of custom nbt of player's tool = 1
	set {_weapon} to string tag "name" of custom nbt of player's tool
	useAbility(player, {_weapon})


on rightclick:
	if clicked entity is a mannequin:
		stop
	if any:
		"%clicked entity%" = "interaction"
		clicked block is a lectern
	then:
		stop


	byte tag "weapon" of custom nbt of player's tool = 1
	set {_weapon} to string tag "name" of custom nbt of player's tool
	set {_attunement} to string tag "attunement" of custom nbt of player's tool

	if any:
		{-tempdata::%uuid of player%::reinforce} = true
		{-tempdata::%uuid of player%::blitz} = true
		{-tempdata::%uuid of player%::shroud} = true
	then:
		set {_buff} to true

	if {_attunement} = "None":
		prioritybar(player, "&8«   &c&lNO ATTUNEMENT EQUIPPED   &8»", 1 second)
		play sound "block.note_block.pling" at pitch 0.5 to player
	
	# ON GROUND
	else if all:
		("quickstep", "thrust", "eruption" and "vortex") contains {_attunement}
		player is not on the ground
	then:
		prioritybar(player, "&8«   &c&lSTAY ON THE GROUND   &8»", 1 second)
		play sound "block.note_block.pling" at pitch 0.5 to player

	# BODY BUFF ACTIVE
	else if all:
		("reinforce", "blitz" and "shroud") contains {_attunement}
		{_buff} = true
	then:
		prioritybar(player, "&8«   &c&lBUFF ALREADY ACTIVE   &8»", 1 second)
		play sound "block.note_block.pling" at pitch 0.5 to player
	
	# ATTUNEMENT COOLDOWNS
	else if all:
		("quickstep", "escape", "parry", "rippleblade", "eruption", "vortex", "reinforce", "blitz" and "shroud") contains {_attunement}
		(player's metadata "cooldown_%{_attunement}%") > now
	then:
		set {_time} to difference between player's metadata "cooldown_%{_attunement}%" and now
		prioritybar(player, "&8«   &c&lATTUNEMENT ON COOLDOWN &8(&e%formatTime({_time})%&8)   &8»", 1 second)
		play sound "block.note_block.pling" at pitch 0.5 to player

	else:
		useAbility(player, {_weapon}, {_attunement})





# equip/unequip onimaru
on tool change:
	set player's attack speed attribute to 4
	wait 1 tick
	actionbar(player)

	# equip
	uncolored name of player's tool = "Onimaru [🗡]":
		{data::%uuid of player%::options::dual onimaru} is not set
		set {_i} to getWeapon("onimaru", "hidden")
		modify custom nbt of {_i}:
			set byte tag "weapon" of nbt to 0
			set byte tag "offhand" of nbt to 1
			set string tag "name" of nbt to "onimaru"
			set string tag "model-suffix" of nbt to "_offhand"
		set {_model} to item model of {_i}
		replace all "main" in {_model} with "offhand"
		set item model of {_i} to {_model}

		if number of netherite sword in player's inventory > 2:
			remove 99 of {_i} from player's inventory
		
		if player's offhand tool is not a netherite sword:
			give player player's offhand tool
		set player's offhand tool to {_i}
	
	# unequip
	else:
		uncolored name of player's offhand tool = "Onimaru [🗡]"
		item model of (player's offhand tool) contains "offhand"
		set player's offhand tool to air
