

options:
	npc: location(0.5, 80, -481.5, world "runeblade", 180, 0)




on load:


	delete bound from id "tutorial.secondaries"
	delete bound from id "tutorial.combos"


	create a temporary bound with id "tutorial.secondaries" between ({@npc} ~ vector(5, 0, 31.5)) and ({@npc} ~ vector(-5, 6, 48))
	create a temporary bound with id "tutorial.combos" between ({@npc} ~ vector(26.5, 0, -2.5)) and ({@npc} ~ vector(41.5, 6, 12.5))










function displayMessage(p: player, prefix: string, message: string, ping: boolean=false):

	play sound "block.note_block.hat" at volume 10 to {_p}
	if {_ping} = true:
		play sound "entity.experience_orb.pickup" at volume 10 to {_p}

	send "" to {_p}
	send "  %{_prefix}% &8» %{_message}%" to {_p}
	send "" to {_p}














command /tutorial:
	trigger:

		if {-tempdata::%uuid of player%::tutorial} is set:
			send "%prefix()% You're already in the tutorial! Rejoin if you're bugged!" to player
			play sound "block.note_block.didgeridoo" at pitch 0.5 to player
		
		else:
			startTutorial(player)






function startTutorial(p: player):

	close {_p}'s inventory
	set {_start} to {@npc} ~ vector(0, 0, -19)
	set {_start}'s yaw to 0
	teleport {_p} to {_start}
    
	apply blindness 1 to {_p} for 30 ticks:
		hide particles
		hide icon

	set {_p}'s gamemode to adventure
	clear {_p}'s inventory
	if {data::%uuid of {_p}%::equipped::armour} is set:
		equipArmour({_p})
	else:
		equipArmour({_p}, "iron")
	

	wait 5 ticks

	loop (all mobs in radius 128 of {@npc}) where [string tag "owner" of custom nbt of input is set]:
		# arg-1 will fetch player, arg-2 is obj to hide
		set {_user} to string tag "owner" of custom nbt of loop-value
		hideEntityWithinScope({_user}, loop-value)


	reveal {-registry::npc::Tutorial Swordsmith::*} to {_p}

	hide {-registry::npc::Tutorial Attunement Master::*} from {_p}
	hide {-display::tutorial::*} from {_p}

	send title "&7« %servername()% &7»" with subtitle "&cSword &7and &3Magic &7PVP" to {_p}

	# seal doors
	make {_p} see (blocks within {@npc} ~ vector(1, 0, 31) and {@npc} ~ vector(-1, 4, 31)) as black concrete
	make {_p} see (blocks within {@npc} ~ vector(26, 0, 4) and {@npc} ~ vector(26, 4, 6)) as black concrete
	
	play sound "entity.player.levelup" at volume 10 to {_p}
	play sound "block.note_block.flute" at volume 10 at pitch 2 to {_p}

	set {-tempdata::%uuid of {_p}%::tutorial} to 0
	clear {-tempdata::%uuid of {_p}%::tutorial::*}

	wait 1.5 seconds

	displayMessage({_p}, "&a&lTUTORIAL", "&7Welcome to &eRuneblade&7! Talk to the &cSwordsmith &7to begin!")

	while {-tempdata::%uuid of {_p}%::tutorial} = 0:

		set {_init} to location of {_p} ~ vector(0, 1, 0)
		set {_v} to vector from {_init} and {@npc}
		set {_len} to {_v}'s vector length
		set {_v}'s vector length to 1
		set {_temp} to {_v}
		set {_temp}'s vector length to {_len}
		set {_draw} to {_init}


		loop {_len} times:

			set {_draw} to {_draw} ~ {_v}
			set {_temp}'s vector length to distance between {_draw} and {@npc}
			force draw 0 wax off particles with offset {_temp} with extra value 2 at {_draw} to {_p}

		exit loop if loop-counter > 1000
		stop if {_p} is not connected
		
		wait 1 second






function updateTutorial(p: player, type: text):

	set {_scope::*} to getScope({_p})
	broadcast "Scope is"

	if {_type} = "attunement":

		if size of (items in {_p}'s inventory) where [byte tag "weapon" of custom nbt of input = 1] >= 2:
			close {_p}'s inventory
			set {-tempdata::%uuid of {_p}%::tutorial} to 1
		
			hide {-registry::npc::Tutorial Swordsmith::*} from {_p}

			draw 25 large smoke particles with extra value 0.15 at (location of {_ent} ~ vector(0, 0.75, 0)) for {_scope::*}
			draw 10 flame particles with extra value 0.1 at (location of {_ent} ~ vector(0, 0.75, 0)) for {_scope::*}
			draw 8 lava particles with extra value 0.15 at (location of {_ent} ~ vector(0, 0.75, 0)) for {_scope::*}
			play sound "block.fire.extinguish" at volume 10 at location of {_ent} to {_p}


			wait 2 second

			displayMessage({_p}, "&a&lTUTORIAL", "&7Now that you have your weapons, add an &5Attunement &7to each of them!", true)

			draw 25 large smoke particles with extra value 0.15 at (location of {_ent} ~ vector(0, 0.75, 0)) for {_scope::*}
			draw 20 witch particles with extra value 0.15 at (location of {_ent} ~ vector(0, 0.75, 0)) for {_scope::*}
			play sound "block.fire.extinguish" at volume 10 at location of {_ent} to {_p}

			reveal {-registry::npc::Tutorial Attunement Master::*} to {_p} # show attunement master



	else if {_type} = "dummy":

		{-tempdata::%uuid of {_p}%::tutorial} != 2 # debug

		set {_size} to size of (((items in {_p}'s inventory) where [byte tag "weapon" of custom nbt of input = 1]) where [string tag "attunement" of custom nbt of input != "none"])
		if {_size} >= 2:
			set {-tempdata::%uuid of {_p}%::tutorial} to 2

			wait 1 tick
			close {_p}'s inventory
			

			hide {-registry::npc::Tutorial Attunement Master::*} from {_p}

			draw 25 large smoke particles with extra value 0.15 at (location of {_ent} ~ vector(0, 0.75, 0)) for {_scope::*}
			draw 20 witch particles with extra value 0.15 at (location of {_ent} ~ vector(0, 0.75, 0)) for {_scope::*}
			play sound "block.fire.extinguish" at volume 10 at location of {_ent} to {_p}

			wait 2 second

			displayMessage({_p}, "&a&lTUTORIAL", "&7Let's put those tools to the test! &e&lLEFT-CLICK &7to &fAttack &7and &e&lRIGHT-CLICK &7to use your &5Attunement&7!", true)

			draw 25 large smoke particles with extra value 0.15 at (location of {_ent} ~ vector(0, 0.75, 0)) for {_scope::*}
			draw 10 angry villager particles with offset vector(0.3, 0.3, 0.3) at (location of {_ent} ~ vector(0, 0.75, 0)) for {_scope::*}
			play sound "block.fire.extinguish" at volume 10 at location of {_ent} to {_p}

			spawn adult husk at {@npc}:
				set {_ent} to husk
				modify custom nbt of husk:
					set byte tag "mob" of nbt to 1
					set int tag "tutorial" of nbt to 2
				set byte tag "Silent" of nbt of husk to 1

				set husk's generic armor attribute to 0
				apply infinite weakness 255 to husk:
					hide particles
				apply invisibility 1 to husk for 5 ticks:
					hide particles
				set husk's maximum health to 10
				set ai of husk to false
				heal husk
			
			wait 1 tick
			set string tag "owner" of custom nbt of {_ent} to name of {_p}
			hideEntityWithinScope({_p}, {_ent})
			
			wait 3 minutes
			kill {_ent}

			if {_p} is online:
				{-tempdata::%uuid of {_p}%::tutorial} = 2
				updateTutorial({_p}, "attunement")


	else if {_type} = "knight" or "respawn":
		kill (all zombies in radius 256 of {@npc}) where [string tag "owner" of custom nbt of input = name of {_p}]
		set {-tempdata::%uuid of {_p}%::tutorial} to 3

		wait 2 second

		if {_type} = "knight":
			displayMessage({_p}, "&a&lTUTORIAL", "&7Now you've beaten up a dummy, try it out on the real thing!", true)
		else if {_type} = "respawn":
			displayMessage({_p}, "&a&lTUTORIAL", "&7If you're struggling, try slowing down your attacks or using your bow!", true)

		wait 2 second

		loop ({@npc} ~ vector(23, 0, 5)), ({@npc} ~ vector(-23, 0, 5)):
			spawn_knight(loop-value, 1)
			set {_ent} to nearest zombie at loop-value

			modify custom nbt of {_ent}:
				set string tag "owner" of nbt to "%{_p}%"
				set int tag "tutorial" of nbt to 3

			hideEntityWithinScope({_p}, {_ent})
			apply glowing 1 to {_ent} for 3 seconds:
				hide particles
			set {_ent}'s target to {_p}

			draw 25 large smoke particles with extra value 0.15 at (location of {_ent} ~ vector(0, 0.75, 0)) for {_scope::*}
			play sound "block.fire.extinguish" at volume 3 at location of {_ent} to {_p}
			play sound "entity.zombie_villager.cure" at volume 3 at pitch 1.5 at location of {_ent} to {_p}


	else if {_type} = "finish":

		wait 1 second

		{-tempdata::%uuid of {_p}%::tutorial} < 4
		set {_size} to size of ((all zombies in radius 256 of {@npc}) where [string tag "owner" of custom nbt of input = name of {_p}])
		{_size} = 0
		set {-tempdata::%uuid of {_p}%::tutorial} to 4

		displayMessage({_p}, "&a&lTUTORIAL CLEARED", "&7Well done! You've now beaten the main tutorial.", true)

		set slot 7 of {_p}'s inventory to clock named "&e&lEXIT TUTORIAL" with lore "", formatParagraph("Ready to leave the tutorial? Click to use."), ""

		wait 3 seconds

		{-tempdata::%uuid of {_p}%::tutorial} is set
		displayMessage({_p}, "&a&lTUTORIAL", "&7If you want to learn more about the game's mechanics, explore around some more!")

		# unseal doors
		reveal {-display::tutorial::*} to {_p}
		make {_p} see (blocks within {@npc} ~ vector(1, 0, 31) and {@npc} ~ vector(-1, 4, 31)) as air
		make {_p} see (blocks within {@npc} ~ vector(26, 0, 4) and {@npc} ~ vector(26, 4, 6)) as air

		wait 4 seconds

		{-tempdata::%uuid of {_p}%::tutorial} is set
		displayMessage({_p}, "&a&lTUTORIAL", "&7If you feel ready to move on, &e&lRIGHT-CLICK &7with the clock!")






	else if {_type} = "secondaries_start":
		
		{-tempdata::%uuid of {_p}%::tutorial} != 5
		{-tempdata::%uuid of {_p}%::tutorial::secondaries} != true
		set {-tempdata::%uuid of {_p}%::tutorial} to 5

		wait 0.5 second

		{-tempdata::%uuid of {_p}%::tutorial} = 5
		displayMessage({_p}, "&a&lTUTORIAL", "&7Secondaries! Everyone has their sword and a secondary magic tool by their side.", true)
		wait 4 seconds

		{-tempdata::%uuid of {_p}%::tutorial} = 5
		displayMessage({_p}, "&a&lTUTORIAL", "&7Using a secondary costs <#2eadd7>&lMANA <#2eadd7>★&7, visible above your hotbar.")
		wait 4 seconds

		{-tempdata::%uuid of {_p}%::tutorial} = 5
		displayMessage({_p}, "&a&lTUTORIAL", "&7If you wait too long between attacks, your combo resets! Make sure you space your attacks out!")
		wait 5.5 seconds

		{-tempdata::%uuid of {_p}%::tutorial} = 5
		displayMessage({_p}, "&a&lTUTORIAL", "&7Try killing a dummy with your secondary! &e&lLEFT-CLICK &7with your bow to attack!")
		
		set {_loc} to {@npc} ~ vector(0, 0, 43.25)
		draw 25 large smoke particles with extra value 0.15 at ({_loc} ~ vector(0, 0.75, 0)) for {_scope::*}
		draw 10 angry villager particles with offset vector(0.3, 0.3, 0.3) at ({_loc} ~ vector(0, 0.75, 0)) for {_scope::*}
		play sound "block.fire.extinguish" at volume 10 at {_loc} to {_p}

		spawn adult husk at {_loc}:
			set {_ent} to husk
			modify custom nbt of husk:
				set string tag "owner" of nbt to "%{_p}%"
				set byte tag "mob" of nbt to 1
				set int tag "tutorial" of nbt to 5
			set byte tag "Silent" of nbt of husk to 1

			set husk's generic armor attribute to 0
			apply infinite weakness 255 to husk:
				hide particles
			apply invisibility 1 to husk for 5 ticks:
				hide particles
			set husk's maximum health to 5
			set ai of husk to false
			heal husk
		
		wait 1 tick
		hideEntityWithinScope({_p}, {_ent})
		
		wait 3 minutes
		kill {_ent}

		if {_p} is online:
			{-tempdata::%uuid of {_p}%::tutorial} = 5
			updateTutorial({_p}, "secondaries_start")
	


	else if {_type} = "secondaries_finish":

		{-tempdata::%uuid of {_p}%::tutorial} = 5
		set {-tempdata::%uuid of {_p}%::tutorial} to 6

		wait 1 second

		{-tempdata::%uuid of {_p}%::tutorial} = 6
		displayMessage({_p}, "&a&lTUTORIAL", "&7You can buy different secondaries later when you gather <##2eadd7>₪ &fRunes &7by killing other players or from clearing dungeons.")
		wait 4 seconds

		{-tempdata::%uuid of {_p}%::tutorial} = 6
		displayMessage({_p}, "&a&lTUTORIAL", "&7Some secondaries focus more on range, while others help out in close combat! Be sure to find which secondary fits your playstyle!")
		wait 4 seconds

		{-tempdata::%uuid of {_p}%::tutorial} = 6
		displayMessage({_p}, "&a&lTUTORIAL CLEARED", "&7Make sure to visit the other tutorials to get more info on how to combo with your secondary and how to conserve your mana!", true)
		set {-tempdata::%uuid of {_p}%::tutorial} to 4
		set {-tempdata::%uuid of {_p}%::tutorial::secondaries} to true

		



	else if {_type} = "combos_start":
		
		{-tempdata::%uuid of {_p}%::tutorial} != 7
		{-tempdata::%uuid of {_p}%::tutorial::combos} != true
		set {-tempdata::%uuid of {_p}%::tutorial} to 7

		wait 0.5 second

		{-tempdata::%uuid of {_p}%::tutorial} = 7
		displayMessage({_p}, "&a&lTUTORIAL", "&7Your sword swings don't always deal their full damage!", true)
		wait 4 seconds

		{-tempdata::%uuid of {_p}%::tutorial} = 7
		displayMessage({_p}, "&a&lTUTORIAL", "&7If you click too fast, your sword deals less damage than if you waited.")
		wait 4 seconds

		{-tempdata::%uuid of {_p}%::tutorial} = 7
		displayMessage({_p}, "&a&lTUTORIAL", "&7Try timing your attacks on the dummy for full damage combo!")
		
		set {_loc} to {@npc} ~ vector(37, 0, 5)
		set {_loc}'s yaw to 90
		draw 25 large smoke particles with extra value 0.15 at ({_loc} ~ vector(0, 0.75, 0)) for {_scope::*}
		draw 10 angry villager particles with offset vector(0.3, 0.3, 0.3) at ({_loc} ~ vector(0, 0.75, 0)) for {_scope::*}
		play sound "block.fire.extinguish" at volume 10 at {_loc} to {_p}

		spawn adult husk at {_loc}:
			set {_ent} to husk
			modify custom nbt of husk:
				set string tag "owner" of nbt to "%{_p}%"
				set byte tag "mob" of nbt to 1
				set int tag "tutorial" of nbt to 7
			set byte tag "Silent" of nbt of husk to 1

			set husk's generic armor attribute to 0
			apply infinite weakness 255 to husk:
				hide particles
			apply invisibility 1 to husk for 5 ticks:
				hide particles
			set husk's maximum health to 100
			set ai of husk to false
			heal husk
		apply regeneration 5 to {_ent} for 5 minutes:
			hide particles
		
		wait 1 tick
		hideEntityWithinScope({_p}, {_ent})
		
		wait 3 minutes
		kill {_ent}

		if {_p} is online:
			{-tempdata::%uuid of {_p}%::tutorial} = 7
			updateTutorial({_p}, "combos_start")
	



	else if {_type} = "combos_finish":

		{-tempdata::%uuid of {_p}%::tutorial} = 7
		set {-tempdata::%uuid of {_p}%::tutorial} to 8

		wait 1 second

		{-tempdata::%uuid of {_p}%::tutorial} = 8
		displayMessage({_p}, "&a&lTUTORIAL", "&7That's it! All of your attacks have cooldowns attached to them. &8(&e&osword, bow, attunement&8)")
		wait 4 seconds

		{-tempdata::%uuid of {_p}%::tutorial} = 8
		displayMessage({_p}, "&a&lTUTORIAL", "&7Be sure not to attack too often, otherwise you'll deal almost no damage!")
		wait 4 seconds

		{-tempdata::%uuid of {_p}%::tutorial} = 8
		displayMessage({_p}, "&a&lTUTORIAL", "&7If you want to combo your opponents more, try mixing your bow attacks in with your sword swings!")
		wait 4 seconds

		{-tempdata::%uuid of {_p}%::tutorial} = 8
		displayMessage({_p}, "&a&lTUTORIAL CLEARED", "&7Make sure to visit the other tutorials to get more info on how to play!", true)
		set {-tempdata::%uuid of {_p}%::tutorial} to 4
		set {-tempdata::%uuid of {_p}%::tutorial::combos} to true

		loop all husks in radius 2 of {@npc} ~ vector(37, 0, 5):
			string tag "owner" of custom nbt of loop-value = name of {_p}
			delete loop-value







on target:
	target is a player
	string tag "owner" of custom nbt of event-entity is set

	set {_scope::*} to getScope(event-entity)
	{_scope::*} doesn't contain target
	cancel event
	set event-entity's target to random element out of {_scope::*}


on death of mob:
	victim is a zombie or husk
	attacker is a player
	attacker is online

	set {_val} to int tag "tutorial" of custom nbt of victim
	{_val} is set
	{-tempdata::%uuid of attacker%::tutorial} = {_val}

	# kill dummy husk
	if {_val} = 2:
		updateTutorial(attacker, "knight")
	# finish basic tutorial
	else if {_val} = 3:
		updateTutorial(attacker, "finish")
	# finish secondaries tutorial
	else if {_val} = 5:
		updateTutorial(attacker, "secondaries_finish")


on rightclick with clock:
	name of event-item = "&e&lEXIT TUTORIAL"
	remove event-item from player's inventory
	
	clear {-tempdata::%uuid of player%::tutorial} and {-tempdata::%uuid of player%::tutorial::*}
	set {data::%uuid of player%::tutorial} to true

	teleport player to spawn()
	play sound "ui.button.click" and "entity.enderman.teleport" at volume 10 to player
    
	loop (all mobs in radius 100 of {@npc}) where [string tag "owner" of custom nbt of input = name of player]:
		kill loop-entity



on command:
	{-tempdata::%uuid of player%::tutorial} is set
	command doesn't contain "spawn"
	cancel event
	send "%prefix()% You must finish the tutorial before using commands!" to player
	play sound "block.note_block.didgeridoo" at pitch 0.5 to player

	chance of 15%:
		send "%prefix()% &7Rejoin if you're stuck!" to player



on enter bound with id "tutorial.secondaries":
	{-tempdata::%uuid of player%::tutorial} >= 4
	{-tempdata::%uuid of player%::tutorial::secondaries} != true
	updateTutorial(player, "secondaries_start")

on enter bound with id "tutorial.combos":
	{-tempdata::%uuid of player%::tutorial} >= 4
	{-tempdata::%uuid of player%::tutorial::combos} != true
	updateTutorial(player, "combos_start")