
placeholderapi placeholder with the prefix "runeblade":
	if the identifier is "prefix":
		set the result to player's prefix
	else if the identifier is "name":
		set the result to player's name
	else if the identifier is "health":
		set the result to player's health

	else if the identifier is "suffix":
		if {data::%uuid of player%::equipped::suffixes} is set:
			set the result to raw " <dark_gray>(%raw {-suffixes::%{data::%uuid of player%::equipped::suffixes}%::name}%<dark_gray>)"
		else:
			set the result to ""



function formatMini(str: string) :: string:
	set {_str} to {_str}
	replace all "&l" in {_str} with "<bold>EA</b>"

	return {_str}