


function transientmoonlightAction(p: player, weapon: text, atk-scale: number):
	set {_hit} to 1

	set {_particle-scale::1} to 1.6
	set {_particle-scale::2} to 1.8
	set {_particle-scale::3} to 2

	set {_windup-time} to 10

	set {_dmg} to getDamage({_p}, {_weapon}, {_hit}, "transient moonlight") * {_atk-scale}
	set {_sound-scale} to (-1 * {_atk-scale}) + 1

	play sound "entity.illusioner.prepare_mirror" at volume 3 at pitch 2 at {_p}
	play sound "entity.evoker.cast_spell" at volume 3 at pitch 2 at {_p}
	play sound "sword.sheen" at volume 3 at pitch 1.25+{_sound-scale} at {_p}
	play sound "elemental.magic" at volume 3 at pitch 1.5+{_sound-scale} at {_p}

	# windup
	loop {_windup-time} times:
		loop 90 times:
			set {_v} to spherical vector from radius (loop-value-1 / 5), yaw (loop-value-2 * 4) and pitch 0
			draw 1 {-colours::%{_weapon}%::1::1} dust particles that transitions to {-colours::%{_weapon}%::1::3} at location 0.05 above {_p} ~ {_v}

		wait 1 tick



	set {_dir} to -1
	set {_arc} to 100
	set {_angle} to 90 + random number between -5 and 5 - ({_p}'s pitch * 0.33)
	set {_yaw} to {_p}'s yaw
	set {_pitch} to {_p}'s pitch
	set {_hitbox} to round({_arc}/3)

	set {_arc::1::*} to baseArc({_yaw}, {_pitch}-5, 4.6, {_dir}, {_arc}, 1, {_angle})
	set {_arc::2::*} to baseArc({_yaw}, {_pitch}, 5, {_dir}, {_arc}, 1, {_angle})
	set {_arc::3::*} to baseArc({_yaw}, {_pitch}-5, 5.4, {_dir}, {_arc}, 1, {_angle})

	play sound "entity.player.attack.sweep" at volume 3 at pitch 0.5+{_sound-scale} at {_p}
	play sound "item.trident.throw" at volume 3 at pitch 0.65+{_sound-scale} at {_p}
	play sound "entity.iron_golem.attack" at volume 2.6 at pitch 0.5+{_sound-scale} at {_p}
	play sound "entity.trident.return" at volume 0.5 at pitch 0.6+{_sound-scale} at {_p}
	play sound "entity.iron_golem.damage" at volume 1.25 at pitch 0.5+{_sound-scale} at {_p}
	play sound "sword.heavy_slash" at volume 3 at pitch 1.5+{_sound-scale} at {_p}
	play sound "sword.whoosh" at volume 3 at pitch 1.5+{_sound-scale} at {_p}
	play sound "elemental.magic_aura" at volume 3 at pitch 2+{_sound-scale} at {_p}

	set {-tempdata::%uuid of {_p}%::stunned} to true
	make {_p} swing their main hand

	set {_wave-v} to vector from yaw {_yaw} and pitch {_pitch}
	set {_wave-v}'s vector length to 0.5

	set {_draw} to location 0.5 infront of {_p}'s head
	loop 20 times:
		loop {_arc} times:

			# main slash
			loop-value-1 = 1:
				set {_loop-scale} to max(1, (loop-value-2 * -0.01666) + 1.65)
				loop 3 times:
					set {_particle-scale} to {_particle-scale::%loop-value-3%} * {_loop-scale}
					set {_col} to {-colours::%{_weapon}%::1::%loop-value-3%} ? {-colours::%{_weapon}%::1::1}
					draw 1 {_col} dust particles of size {_particle-scale} at {_draw} ~ {_arc::%loop-value-3%::%loop-value-2%}
				chance of 30%:
					set {_v} to {_arc::2::%loop-value-2%}
					add {_angle} to {_v}'s pitch
					set {_rand} to random vector
					set {_rand}'s vector length to 0.2
					draw 0 enchanted hit particles with offset {_v} with extra value 0.2 at {_draw} ~ {_arc::2::%loop-value-2%} ~ {_rand}
			

				mod(loop-value-2, {_hitbox}) = 0:
					loop entities in radius 2.5 of ({_draw} ~ {_arc::2::%loop-value-2%}) where [input != {_p}]:
						isDamageableEntity(loop-entity, {_p}) = true
						{_hit::*} doesn't contain loop-entity
						set {_hit::%uuid of loop-entity%} to loop-entity

						play sound "entity.player.attack.crit" at pitch 1.2 at {_p}

						hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon}, "transient moonlight")
						make {_p} damage loop-entity by {_dmg}
						push loop-entity (vector from {_p} to loop-entity) at speed 0.4 * {_atk-scale}
						push loop-entity up at speed 0.25 * {_atk-scale}
						
					
					loop entities in radius 2.5 of (location 1.5 infront of {_p}'s head) where [input != {_p}]:
						isDamageableEntity(loop-entity, {_p}) = true
						{_hit::*} doesn't contain loop-entity
						set {_hit::%uuid of loop-entity%} to loop-entity

						play sound "entity.player.attack.crit" at pitch 1.2 at {_p}

						hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon}, "transient moonlight")
						make {_p} damage loop-entity by {_dmg}
						push loop-entity (vector from {_p} to loop-entity) at speed 0.4 * {_atk-scale}
						push loop-entity up at speed 0.25 * {_atk-scale}
						



			# wave
			mod(loop-value-2, 4) = 0:
				set {_loop-scale} to max(1, (loop-value-2 * -0.01666) + 1.65)
				loop 3 times:
					set {_particle-scale} to ({_particle-scale::%loop-value-3%} * {_loop-scale}) - (loop-value-1 * 0.075)
					set {_col} to {-colours::%{_weapon}%::1::%loop-value-3%} ? {-colours::%{_weapon}%::1::1}
					draw 1 {_col} dust particles of size {_particle-scale} at {_draw} ~ {_arc::%loop-value-3%::%loop-value-2%}

			# wave hitbox
			loop-value-1 > 2:
				mod(loop-value-2, {_hitbox}) = 0:
					loop entities in radius 2.5 of ({_draw} ~ {_arc::2::%loop-value-2%}) where [input != {_p}]:
						isDamageableEntity(loop-entity, {_p}) = true
						{_hit::*} doesn't contain loop-entity
						set {_hit::%uuid of loop-entity%} to loop-entity

						play sound "entity.player.attack.crit" at pitch 1.2 at {_p}

						hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon}, "transient moonlight")
						make {_p} damage loop-entity by {_dmg} * 0.6
						push loop-entity (vector from {_p} to loop-entity) at speed 0.4 * {_atk-scale}
						push loop-entity up at speed 0.25 * {_atk-scale}
						


			loop-value-1 = 1:
				mod(loop-value-2, 45) = 0
				wait 1 tick
			
		

		set {_draw} to {_draw} ~ {_wave-v}
		loop-value-1 != 1:
			mod(loop-value-2, 3) = 0
			wait 1 tick
	
	clear {-tempdata::%uuid of {_p}%::stunned}


