


function blitzAction(p: player, weapon: string, atk-scale: number):
	set {_sound-scale} to (-1 * {_atk-scale}) + 1
	set {-tempdata::%uuid of {_p}%::blitz} to true

	set {_grad} to minimessage from "<gradient:##545454:##FFff55>--------------------"
	set {_spl::*} to raw {_grad} split at "-"

	spawn text display at {_p}:
		set {_ent} to text display
		add {_ent} to {_p}'s passengers
		set text of {_ent} to "&8« &6&lBLITZ &8»"
		set transformation translation of {_ent} to vector(0, 0.8, 0)
		set transformation scale of {_ent} to vector(1.25, 1.25, 1.25)
		set billboard of {_ent} to center

	play sound "block.beacon.deactivate" at volume 1.5 at pitch 1.5+{_sound-scale} at {_p}
	play sound "entity.firework_rocket.blast" at volume 1 at pitch 1.5+{_sound-scale} at {_p}

	# windup
	loop 40 times:
		mod(loop-value,2) = 0:
			set text of {_ent} to formatted "&8« %{_spl::%loop-value / 2%}%&lBLITZ &8»"
		draw 2 smoke particles with offset vector(0.3, 0.3, 0.3) with extra value 0.1 at location 1 above {_p}
		draw 2 electric spark particles with offset vector(0.5, 0.5, 0.5) with extra value 0.25 at location 1 above {_p}
		wait 1 tick	

	play sound "entity.generic.explode" at volume 1 at pitch 1.6 at {_p}
	play sound "entity.lightning_bolt.impact" at volume 0.75 at pitch 1.5+{_sound-scale} at {_p}
	play sound "entity.blaze.shoot" at volume 1 at pitch 0.6+{_sound-scale} at {_p}
	play sound "elemental.lightning" at volume 1.5 at pitch 1.5+{_sound-scale} at {_p}
	draw 2 white flash particles at location 1 above {_p}
	draw 20 wax off particles with offset vector(0.5, 0.5, 0.5) with extra value 0.5 at location 1 above {_p}


	# 7.5s duration
	loop 30 times:
		draw 4 electric spark particles with offset vector(0.5, 0.5, 0.5) with extra value 0.25 at location 1 above {_p}
		wait 5 ticks
	
	loop reversed 20 times:
		set text of {_ent} to formatted "&8« %{_spl::%loop-value%}%&lBLITZ &8»"
		draw 2 smoke particles with offset vector(0.5, 0.5, 0.5) with extra value 0.1 at location 1 above {_p}
		draw 2 electric spark particles with offset vector(0.5, 0.5, 0.5) with extra value 0.25 at location 1 above {_p}
		play sound "entity.iron_golem.repair" at volume 0.3 at pitch 0.5+loop-value/20 at {_p}
		wait 1 tick

	play sound "entity.generic.explode" at volume 1 at pitch 0.8 at {_p}
	play sound "entity.lightning_bolt.impact" at volume 0.75 at pitch 1+{_sound-scale} at {_p}
	play sound "entity.blaze.shoot" at volume 1 at pitch 0.6+{_sound-scale} at {_p}
	play sound "block.beacon.deactivate" at volume 1.5 at pitch 0.5+{_sound-scale} at {_p}
	play sound "entity.firework_rocket.blast" at volume 1 at pitch 0.5+{_sound-scale} at {_p}
	play sound "entity.firework_rocket.large_blast" at volume 1 at pitch 0.5+{_sound-scale} at {_p}

	draw 20 wax on particles with offset vector(0.5, 0.5, 0.5) with extra value 0.5 at location 1 above {_p}


	clear {-tempdata::%uuid of {_p}%::blitz}
	kill {_ent}
	set {_p}'s metadata "cooldown_blitz" to 15 seconds from now
	prioritybar({_p}, "&8«   &e&lBLITZ &7has expired!   &8»", 1 second)