


function flamedanceAction(p: player, weapon: string, atk-scale: number):

	set {_particle-scale::1} to 1
	set {_particle-scale::2} to 1.2
	set {_particle-scale::3} to 1.4

	set {_dmg} to getDamage({_p}, {_weapon}, {_hit}, "flame dance") * {_atk-scale}
	set {_palette} to getWeaponColour({_p}, {_weapon})
	set {_sound-scale} to (-1 * {_atk-scale}) + 1

	set {_windup-time} to 9 # ticks
	set {_div} to {_windup-time} / 2

	play sound "sword.whoosh" at volume 2 at pitch 1+{_sound-scale} at {_p}
	# windup
	loop {_windup-time} times:
		mod(loop-value, 4) = 0:
			play sound "block.fire.extinguish" at volume 0.75 at pitch 0.6+(loop-value/27)+{_sound-scale} at {_p}

		loop 90 times:
			set {_v} to spherical vector from radius (loop-value-1 / {_div}), yaw (loop-value-2 * 4) and pitch 0
			draw 1 {-colours::%{_palette}%::1::2} dust particles that transitions to {-colours::%{_palette}%::2::1} at location 0.05 above {_p} ~ {_v}

		loop-value = {_windup-time} - 1:
			set {_init} to location of {_p}
		wait 1 tick


	# momentum scaling
	set {_future} to location of {_p}
	set {_v} to vector from {_init} to {_future}
	set {_v}'s vector length to ({_v}'s vector length*{momentum-offset})
	set {_draw} to location 0.5 behind {_p}'s head ~ {_v}

	set {_dir} to -1
	set {_arc} to 100
	set {_angle} to -25 + random number between -5 and 5 - ({_p}'s pitch * 0.33)
	set {_yaw} to {_p}'s yaw - 5
	set {_pitch} to {_p}'s pitch
	set {_hitbox} to round({_arc}/3)

	set {_arc::1::*} to baseArc({_yaw}, {_pitch}, 2.9, {_dir}, {_arc}, 1, {_angle}+2.5)
	set {_arc::2::*} to baseArc({_yaw}, {_pitch}, 3.1, {_dir}, {_arc}, 1, {_angle})
	set {_arc::3::*} to baseArc({_yaw}, {_pitch}, 3.3, {_dir}, {_arc}, 1, {_angle}-2.5)

	play sound "entity.player.attack.sweep" at volume 2 at pitch 0.8+{_sound-scale} at {_p}
	play sound "entity.blaze.shoot" at volume 1.6 at pitch 0.75+{_sound-scale} at {_p}
	play sound "entity.blaze.death" at volume 1.6 at pitch 0.75+{_sound-scale} at {_p}
	play sound "entity.iron_golem.attack" at volume 2 at pitch 0.8+{_sound-scale} at {_p}
	play sound "item.trident.throw" at volume 2 at pitch 1.6+{_sound-scale} at {_p}
	play sound "sword.heavy_slash" at volume 2 at pitch 1.5+{_sound-scale} at {_p}
	play sound "elemental.flames" at volume 2 at pitch 1.5+{_sound-scale} at {_p}

	set {-tempdata::%uuid of {_p}%::stunned} to true
	make {_p} swing their main hand

	loop {_arc} times:

		set {_loop-scale} to max(1, (loop-value * -0.03) + 1.6)
		loop 3 times:
			set {_particle-scale} to {_particle-scale::%loop-value-2%} * {_loop-scale}
			draw 1 {-colours::%{_palette}%::1::%loop-value-2%} dust particles of size {_particle-scale} at {_draw} ~ {_arc::%loop-value-2%::%loop-value-1%}		
		set {_temp-draw} to {_draw} ~ {_arc::2::%loop-value%}
		chance of 15%:
			set {_temp-v} to {_arc::2::%loop-value-1%}
			set {_ref} to vector from yaw {_yaw} and pitch {_pitch}+90
			set {_rand} to random vector
			set {_rand}'s vector length to 0.25
			rotate {_temp-v} around {_ref} by {_arc}
			draw 0 smoke particles with offset {_temp-v} with extra value 0.1 at {_temp-draw} ~ {_rand}
			set {_rand} to random vector
			set {_rand}'s vector length to 0.25
			draw 0 flame particles with offset ({_arc::2::%loop-value-1%} + random vector) with extra value 0.15 at {_temp-draw} ~ {_rand}
		chance of 3%:
			draw 1 lava particles at {_temp-draw}

		# hitbox
		mod(loop-value, {_hitbox}) = 0:
			loop entities in radius 2.5 of ({_temp-draw}) where [input != {_p}]:
				isDamageableEntity(loop-entity, {_p}) = true
				{_hit::*} doesn't contain loop-entity
				set {_hit::%uuid of loop-entity%} to loop-entity

				play sound "entity.blaze.hurt" at pitch 1.5 at {_p}

				hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon}, "flame dance")
				make {_p} damage loop-entity by {_dmg}
				ignite loop-entity for 20 ticks
				push loop-entity (vector from {_p} to loop-entity) at speed 0.8 * {_atk-scale}
				push loop-entity up at speed 0.25 * {_atk-scale}


		mod(loop-value, 20) = 0:
			set {_v} to {_arc::2::%loop-value%}
			set {_v}'s vector length to 0.5
			add (vector from yaw {_yaw} and pitch {_pitch}) to {_v}
			flamedance_projectile({_p}, {_temp-draw}, {_v}, {_weapon})
			wait 1 tick

	clear {-tempdata::%uuid of {_p}%::stunned}


function flamedance_projectile(p: player, loc: location, v: vector, weapon: string):
	drop blaze powder named "%random number between 0 and 99999%" at {_loc}
	set {_ent} to dropped item
	modify nbt of {_ent}:
		set short tag "Age" of nbt to 5800
		set short tag "PickupDelay" of nbt to 32767
	push {_ent} {_v} at speed 0.6
	
	wait 1 tick

	while {_ent} isn't on ground:
		loop entities in radius 1.75 of {_ent} where [input is not a dropped item]:
			loop-entity != {_p}
			isDamageableEntity(loop-entity, {_p}) = true

			hitCombo({_p}, 1, {_weapon}, "flame dance")
			make {_p} damage loop-entity by 1
			ignite loop-entity for 20 ticks
			kill {_ent}
			set {_hit} to true
		
		if any:
			{_ent} isn't alive
			loop-counter >= 50
		then:
			exit loop
	
		mod(loop-counter, 8) = 0:
			draw 0 flame particles with offset {_ent}'s velocity with extra value 1 at {_ent}

		exit all loops if {_hit} = true
		wait 1 tick
	
	draw 1 large smoke particles with extra value 0.2 at {_ent}
	draw 3 flame particles with extra value 0.2 at {_ent}
	play sound "entity.blaze.shoot" at {_ent}
	kill {_ent}
