


function quickstepAction(p: player, weapon: text, atk-scale: number):

	set {_sound-scale} to (-1 * {_atk-scale}) + 1
	set {_p}'s metadata "cooldown_quickstep" to 3.25 seconds from now

	play sound "entity.iron_golem.attack" at volume 4 at pitch 1.45+{_sound-scale} at {_p}
	play sound "entity.phantom.flap" at volume 3 at pitch 1.75+{_sound-scale} at {_p}
	play sound "item.trident.riptide_3" at volume 3 at pitch 1.75+{_sound-scale} at {_p}

	setModifier({_p}, "jump", "attunement", -0.2) # not entire jump cancel
	updateModifiers({_p})

	set {_v} to vector from yaw {_p}'s yaw and pitch -5
	set vector length of {_v} to 1.5
	set {_p}'s velocity to {_v}
	set {_p}'s metadata "cooldown_quickstep" to 3.85 seconds from now

	loop 12 times:

		draw 3 crit particles with offset vector(0.5, 0.5, 0.5) with extra value 0.3 at {_p}
		draw 1 poof particles with offset vector(0.3, 0.3, 0.3) with extra value 0.1 at {_p}

		loop-value = 6:
			play sound "entity.breeze.land" at volume 2 at pitch 1+{_sound-scale} at {_p}
			loop 5 times:
				set {_rand} to random vector
				set {_rand}'s vector length to 0.2
				draw 0 campfire signal smoke particles with offset {_v}+{_rand} with extra value 0.2 at ({_p} ~ vector(0,1,0) ~ {_v})

			draw 3 crit particles with offset vector(0.5, 0.5, 0.5) with extra value 0.2 at {_p} ~ vector(0,1,0)

		loop-value = 8:
			set pitch of {_v} to 0
			set vector length of {_v} to 1
			set {_p}'s velocity to {_v}
			removeModifier({_p}, "jump", "attunement")
			updateModifiers({_p})
			
		
		wait 1 tick
