


function ripplebladeAction(p: player, weapon: text, atk-scale: number):


	set {_dmg} to getDamage({_p}, {_weapon}, 1, "rippleblade") * {_atk-scale}
	set {_sound-scale} to (-1 * {_atk-scale}) + 1

	set {_particle-scale::1} to 1.5
	set {_particle-scale::2} to 1.25
	set {_particle-scale::3} to 1

	
	# windup
	loop 45 times:
		set {_draw} to location 0.2 above {_p}
		loop 4 times:
			set {_v} to spherical vector with radius (loop-value-2)/2.5, yaw (loop-value-2*90)+(loop-value-1*8), pitch 0
			set {_v2} to {_v}
			add 90 to {_v2}'s yaw
			set {_t} to {_draw} ~ {_v}

			loop-value-2 = 3:
				
				draw 0 dust plume particles with offset {_v2} with extra value 0.1 at location 0.1 above {_t}
				draw 1 rgb(4,102,200) dust particles that transitions to rgb(2,62,125) at {_t}
				draw 1 splash particles at location 0.1 above {_t}
			else:
				set {_x} to location (loop-value-2 / 8) above {_t}
				draw 0 fishing particles with offset {_v2} with extra value 0.1 at {_x}
				draw 1 splash particles at {_x}
					

		mod(loop-value, 2) = 0:
			play sound "entity.generic.splash" at volume 2.5 at pitch 1+(loop-value / 45) at {_p}
			wait 1 tick


	set {_d::*} to (-1, -1, 1)
	set {_ang::*} to (90, 0, 45)
	set {_push::*} to 0.6, 0.4, 0.6
	set {_wait::*} to (8 ticks), (7 ticks)

	set {-tempdata::%uuid of {_p}%::stunned} to true
	loop 3 times:

		set {_dir} to loop-valueth element out of {_d::*}
		set {_arc} to 100
		set {_angle} to (loop-valueth element out of {_ang::*}) + (random number between -5 and 5) - ({_p}'s pitch * 0.33)
		set {_yaw} to {_p}'s yaw
		set {_pitch} to {_p}'s pitch
		set {_hitbox} to round({_arc}/3)

		set {_arc::1::*} to baseArc({_yaw}, {_pitch}, 3.2, {_dir}, {_arc}, 1, {_angle})
		set {_arc::2::*} to baseArc({_yaw}, {_pitch}, 3.6, {_dir}, {_arc}, 1, {_angle})
		set {_arc::3::*} to baseArc({_yaw}, {_pitch}, 4, {_dir}, {_arc}, 1, {_angle})

		set {_col::1} to rgb(0, 166, 251)
		set {_col::2} to rgb(0, 100, 148)
		set {_col::3} to rgb(0, 53, 84)

		make {_p} swing their main hand
		set {_draw} to location 0.5 infront of {_p}'s head

		play sound "entity.generic.splash" at volume 3 at pitch 1.2+(loop-value / 6)+{_sound-scale} at {_p}
		play sound "entity.player.attack.sweep" at volume 3 at pitch 1+(loop-value / 6)+{_sound-scale} at {_p}
		play sound "item.bucket.fill" at volume 3 at pitch 1.25+(loop-value / 6)+{_sound-scale} at {_p}
		play sound "sword.slash" at volume 3 at pitch 1.4+(loop-value / 12)+{_sound-scale} at {_p}

		push {_p} forwards at speed (loop-valueth element out of {_push::*})

		loop 90 times:
			set {_v} to spherical vector with radius (loop-value-1 / 4), yaw (loop-value-2*4), pitch 0
			set {_t} to {_v}
			add 30 to {_t}'s yaw
			draw 0 fishing particles with offset {_t} with extra value 0.3 at location 0.2 above {_p} ~ {_v}

		loop {_arc} times:
			set {_loop-scale} to max(1, (loop-value-2 * -0.01666) + 1.65)
			loop 3 times:
				set {_particle-scale} to {_particle-scale::%loop-value-3%} * {_loop-scale}
				draw 1 {_col::%loop-value-3%} dust particles of size {_particle-scale} at {_draw} ~ {_arc::%loop-value-3%::%loop-value-2%}
			
			chance of 15%:
				set {_t} to {_draw} ~ {_arc::2::%loop-value-2%}
				set {_v2} to {_arc::2::%loop-value-2%}
				rotate {_v2} around (vector from yaw {_yaw} - 90 and pitch {_pitch}) by 90
				draw 1 splash particles with offset vector(0.3, 0.3, 0.3) at {_t}
				draw 0 fishing particles with offset {_v2} with extra value 0.3 at {_t}


			mod(loop-value-2, {_hitbox}) = 0:
				loop entities in radius 2.5 of ({_draw} ~ {_arc::2::%loop-value-2%}) where [input != {_p}]:
					isDamageableEntity(loop-entity, {_p}) = true
					{_hit::*} doesn't contain loop-entity
					set {_hit::%uuid of loop-entity%} to loop-entity

					play sound "entity.generic.splash" at pitch 0.8 at {_p}

					hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon}, "rippleblade")
					make {_p} damage loop-entity by {_dmg}
					push loop-entity (vector from {_p} to loop-entity) at speed 0.6 * {_atk-scale}
					push loop-entity up at speed 0.25 * {_atk-scale}
				
				loop entities in radius 1.5 of {_draw} where [input != {_p}]:
					isDamageableEntity(loop-entity, {_p}) = true
					{_hit::*} doesn't contain loop-entity
					set {_hit::%uuid of loop-entity%} to loop-entity

					play sound "entity.generic.splash" at pitch 0.8 at {_p}

					hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon}, "rippleblade")
					make {_p} damage loop-entity by {_dmg}
					push loop-entity (vector from {_p} to loop-entity) at speed 0.6 * {_atk-scale}
					push loop-entity up at speed 0.25 * {_atk-scale}



			mod(loop-value-2, 30) = 0:
				wait 1 tick
		
		clear {_hit::*}
		loop-value != 3:
			wait (loop-valueth element out of {_wait::*})
		

	clear {-tempdata::%uuid of {_p}%::stunned}
	set {_p}'s metadata "cooldown_rippleblade" to 3 seconds from now