


function thunderboltAction(p: player, weapon: text, atk-scale: number):

	set {_dmg} to getDamage({_p}, {_weapon}, {_hit}, "thunderbolt") * {_atk-scale}
	set {_sound-scale} to (-1 * {_atk-scale}) + 1
	set {_max-dist} to 12

	setModifier({_p}, "speed", "attunement", -0.2)
	setModifier({_p}, "jump", "attunement", -0.42)
	updateModifiers({_p})

	play sound "item.trident.throw" at volume 3 at pitch 0.8 at {_p}
	play sound "sword.whoosh" at volume 3 at pitch 0.8 at {_p}
	
	set {_tool} to {_p}'s tool
	set {_loc} to location of {_p} offset by vector(0.05, 1.25, 2) using local axes
	set {_loc}'s pitch to 0
	spawn item display at {_loc}:
		set {_ent} to item display
		set item of item display to {_tool}
		set transformation scale of item display to vector(1.3, 1.3, 1.3)
		set right rotation of item display to axisAngle(45, vector(0, 0, 1))
		set transformation translation of item display to vector(0.75, 0, 0.65)
		set item transform of item display to head
		set interpolation duration of {_ent} to 1 ticks
		set name of item display to "Thunderbolt"
	###
	loop 6 times:
		draw 5 cloud particles with offset vector(0.75, 0.25, 0.75) with extra value 0 at location 2.25 above {_loc}
		wait 1 tick

	loop 6 times:

		draw 5 cloud particles with offset vector(0.75, 0.25, 0.75) with extra value 0.01 at location 2.25 above {_loc}

		set {_ent}'s interpolation delay to 0 ticks
		set {_ent}'s transformation translation to vector(0.75, (0.25 * loop-value), 0.65)

		loop-value >= 4:
			set {_ray} to raytrace from {_p} with max distance {_max-dist} with ray size 0.75 while ignoring passable blocks while ignoring all entities where [isDamageableEntity(input, {_p}) = false]
			set {_hit} to raytrace hit entity of {_ray} ? location 1 above raytrace hit block of {_ray} ? location {_max-dist} infront of {_p}
			
			draw 4 cloud particles with offset vector(0.5, 0.1, 0.5) with extra value 0.02 at {_hit}

		wait 1 tick
	###

###
	removeModifier({_p}, "speed", "attunement")
	removeModifier({_p}, "jump", "attunement")
	updateModifiers({_p})

	draw 15 electric spark particles with offset vector(0.35, 0.6, 0.35) with extra value 0.2 at location 1.3 above {_ent}
	draw 1 rgb(255, 255, 135) flash particles at location 2 above {_ent}

	play sound "elemental.lightning" at volume 3.25 at pitch 1.75+{_sound-scale} at {_p}
	play sound "elemental.lightning_strike" at volume 3.25 at pitch 1.75+{_sound-scale} at {_p}

	loop 6 times:
		draw 5 cloud particles with offset vector(0.75, 0.25, 0.75) with extra value 0.01 at location 2.25 above {_loc}

		loop-value <= 3:
			set {_ray} to raytrace from {_p} with max distance {_max-dist} with ray size 0.75 while ignoring passable blocks while ignoring all entities where [isDamageableEntity(input, {_p}) = false]
			set {_hit} to raytrace hit entity of {_ray} ? location 1 above raytrace hit block of {_ray} ? location {_max-dist} infront of {_p}'s head
		
		draw 4 cloud particles with offset vector(0.5, 0.1, 0.5) with extra value 0.02 at {_hit}


		wait 1 tick
	strike lightning effect at {_hit}
	loop entities in radius 3.25 of {_hit} where [input != {_p}]:
		isDamageableEntity(loop-entity, {_p}) = true
		{_hit::*} doesn't contain loop-entity
		set {_hit::%uuid of loop-entity%} to loop-entity

		hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon}, "thunderbolt")
		make {_p} damage loop-entity by {_dmg}
		push loop-entity (vector from {_hit} to loop-entity) at speed 1 * {_atk-scale}
		push loop-entity up at speed 0.4 * {_atk-scale}

		{_push} isn't set:
			set {_push} to true
			set {_v} to vector from {_p} to {_hit}
			add -15 to {_v}'s pitch
			set {_v}'s vector length to 1.75
			set {_p}'s velocity to {_v}

		loop-entity is a player:
			{_challenge} isn't set
			set {_challenge} to true
			if {-tempdata::%uuid of loop-entity%::duel::rune gains} = true:
				set {_changeStats} to true
			else if {-tempdata::%uuid of loop-entity%::duel::in-duel} is set:
				set {_changeStats} to false
			else:
				set {_changeStats} to true
			{_changeStats} = true
			progressChallenge({_p}, "thunderbolt", 1)


	kill {_ent}
###

