


function vortexAction(p: player, weapon: text, atk-scale: number):

	set {_dmg} to getDamage({_p}, {_weapon}, {_hit}, "vortex") * {_atk-scale}
	set {_sound-scale} to (-1 * {_atk-scale}) + 1
	set {_init-height} to {_p}'s y coordinate
	
	set {_tool} to {_p}'s tool
	set {_loc} to location 2.5 above {_p}
	set {_p}'s metadata "cooldown_vortex" to 4 seconds from now

	spawn item display at {_loc}:
		set {_ent} to item display
		set item of item display to {_tool}
		set transformation scale of item display to vector(1.5, 1.5, 1.5)
		set left rotation of item display to axisAngle(90, vector(1, 0, 0))

		set transformation translation of item display to vector(0, 1, 0)
		set item transform of item display to head
		
		set interpolation duration of {_ent} to 1 ticks
		set teleport duration of {_ent} to 1 ticks
		set name of item display to "Vortex"
		make item display ride {_p}

	

	loop 45 times:
		set {_speed} to loop-value ^ 1.3
		set {_scale} to 1 + (loop-value * 0.02)

		set interpolation delay of {_ent} to 0 ticks

		set transformation scale of {_ent} to vector({_scale}, {_scale}, {_scale})
		set right rotation of {_ent} to axisAngle({_speed} * -9, vector(0, 0, 1)) # (-3.14 / 20)

		set {_ent}'s yaw to {_p}'s yaw
		set {_ent}'s pitch to {_p}'s pitch

		draw 1 electric spark particles with offset vector(0.5, 0.5, 0.5) with extra value 0.2 at ({_ent} ~ display translation of {_ent})

		mod(loop-value+5, 10) = 0:
			play sound "elemental.pulse" at volume 3 at pitch 1.25+(loop-value / 40)+{_sound-scale} at location of {_p}

		mod(loop-value, 2) = 0:
			wait 1 tick
	
	set interpolation delay of {_ent} to 0 ticks
	set left rotation of {_ent} to axisAngle(-90, vector(0, 1, 0))
	set right rotation of {_ent} to axisAngle(0, vector(0, 0, 1))

	if {_tool} is a netherite hoe: # doesn't have a texture
		set transformation translation of {_ent} to vector(0.65, 0, 1.4)
	else:
		set {_scale} to {_scale} * 0.8
		set transformation scale of {_ent} to vector({_scale}, {_scale}, {_scale})
		set transformation translation of {_ent} to vector(-0.65, 0, 2.4)


	loop 5 times:
		set interpolation delay of {_ent} to 0 ticks
		set right rotation of {_ent} to axisAngle((-105 + loop-value) * 20, vector(0, 0, 1)) # (-105 + loop-value) * (3.14 / 9)

		draw 2 enchanted hit particles with offset vector(0.35, 0.35, 0.35) with extra value 0.35 at ({_ent} ~ display translation of {_ent})
		wait 1 tick

	set {_max-height} to 0
	while {_p} is not on the ground:
		exit loop if loop-counter >= 60
		set {_max-height} to max({_p}'s y coordinate, {_max-height})

		wait 1 tick
	
	play sound "sword.heavy_slash" at volume 3 at pitch 0.6+{_sound-scale} at location of {_p}
	play sound "elemental.beam" at volume 3 at pitch 1.5+{_sound-scale} at location of {_p}
	
	make {_ent} dismount their vehicle
	set {_draw} to location 2 infront of {_p} ~ vector(0, 0.3, 0)
	set {_draw} to location 0.5 above {_draw} if block at {_draw} is solid
	
	set {_height} to round(({_max-height} - {_init-height}) / 2)*2
	set {_mod} to first element out of clamp(({_height} / 20), 0, 2)
	add {_mod} to {_dmg}

	# hitbox
	loop entities in radius 5 of {_draw} where [input != {_p}]:
		loop-entity != {_ent}
		isDamageableEntity(loop-entity, {_p}) = true

		hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon}, "vortex")
		make {_p} damage loop-entity by {_dmg}
		push loop-entity (vector from {_p} to loop-entity) at speed 1.25
		push loop-entity up at speed 0.55

		play sound "entity.player.attack.strong" at pitch 0.65+{_sound-scale} at loop-entity

	# shockwave particles

	loop 2 times:
		loop 45 times:
			set {_v} to spherical vector with radius 1+loop-value-1, yaw loop-value-2*8, pitch 0
			draw 0 dust plume particles with offset {_v} with extra value 0.3 at {_draw}

			set {_v}'s vector length to 2+loop-value-1
			draw 0 smoke particles with offset {_v} with extra value 0.15 at {_draw}

			set {_v}'s vector length to loop-value-1
			set {_v2} to {_v}
			set {_v2}'s vector length to 2+loop-value-1
			draw 0 electric spark particles with offset {_v2} with extra value 0.8 at {_draw} ~ {_v}

		
	wait 1 second
	draw 7 poof particles with offset vector(0.1, 0.1, 0.1) with extra value 0.1 at {_ent}
	kill {_ent}