

function moonveilAction(p: entity, hit: integer=1, atk-scale: number):

	set {_particle-scale::1} to 0.8
	set {_particle-scale::2} to 1
	set {_particle-scale::3} to 1.2

	set {_weapon} to "moonveil"
	set {_dmg} to getDamage({_p}, {_weapon}, {_hit}) * {_atk-scale}
	set {_sound-scale} to (-1 * {_atk-scale}) + 1


	if {_hit} = 1:
		set {_dir} to 1
		set {_arc} to 90 # arc length
		set {_angle} to -45 + random number between -10 and 10
		set {_yaw} to {_p}'s yaw
		set {_pitch} to {_p}'s pitch
		set {_hitbox} to {_arc}/3

		set {_arc::1::*} to baseArc({_yaw}, {_pitch}, 3.2, {_dir}, {_arc}, 1, {_angle})
		set {_arc::2::*} to baseArc({_yaw}, {_pitch}, 3.5, {_dir}, {_arc}, 1, {_angle})
		set {_arc::3::*} to baseArc({_yaw}, {_pitch}, 3.8, {_dir}, {_arc}, 1, {_angle})

		play sound "entity.player.attack.sweep" at volume 3 at pitch 1.1+{_sound-scale} at {_p}
		play sound "item.trident.throw" at volume 3 at pitch 1.3+{_sound-scale} at {_p}
		play sound "sword.slash" at volume 3 at pitch 1.2+{_sound-scale} at {_p}

		set {_draw} to location of {_p}'s head
		loop {_arc} times:
			
			loop 3 times:
				draw 1 of dust using dustOption({-colours::%{_weapon}%::%{_hit}%::%loop-value-2%}, {_particle-scale::%loop-value-2%}) at {_draw} ~ {_arc::%loop-value-2%::%loop-value-1%}
			
			loop-value > 10:
				chance of 20%
				set {_v} to {_arc::2::%loop-value%}
				set {_ref} to {_arc::2::%loop-value%}
				add 90 to {_ref}'s pitch
				rotate {_v} around {_ref} by -45

				set {_rand} to random vector
				set {_rand}'s vector length to 0.5

				draw 0 of enchanted hit at {_draw} ~ {_arc::3::%loop-value%} with offset {_v}+{_rand} with extra 0.3

			
			# hitbox
			mod(loop-value, {_hitbox}) = 0:
				loop entities in radius 2.75 of ({_draw} ~ {_arc::2::%loop-value%}) where [input != {_p}]:
					isDamageableEntity(loop-entity, {_p}) = true
					{_hit::*} doesn't contain loop-entity

					hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon})
					make {_p} damage loop-entity by {_dmg}
					push loop-entity (vector from {_p} to loop-entity) at speed 0.5 * {_atk-scale}
					push loop-entity up at speed 0.35 * {_atk-scale}
					add loop-entity to {_hit::*}



			mod(loop-value,20) = 0
			wait 1 tick
	


	else if {_hit} = 2:
		set {_hit} to 1 # used for particles

		set {_dir} to -1
		set {_arc} to 90 # arc length
		set {_angle} to -45 + random number between -10 and 10
		set {_yaw} to {_p}'s yaw
		set {_pitch} to {_p}'s pitch
		set {_hitbox} to {_arc}/3

		set {_arc::1::*} to baseArc({_yaw}, {_pitch}, 3.2, {_dir}, {_arc}, 1, {_angle})
		set {_arc::2::*} to baseArc({_yaw}, {_pitch}, 3.5, {_dir}, {_arc}, 1, {_angle})
		set {_arc::3::*} to baseArc({_yaw}, {_pitch}, 3.8, {_dir}, {_arc}, 1, {_angle})

		play sound "entity.player.attack.sweep" at volume 3 at pitch 0.75+{_sound-scale} at {_p}
		play sound "item.trident.throw" at volume 3 at pitch 0.9+{_sound-scale} at {_p}
		play sound "sword.slash" at volume 3 at pitch 1+{_sound-scale} at {_p}

		set {_draw} to location of {_p}'s head
		loop {_arc} times:
			
			loop 3 times:
				draw 1 of dust using dustOption({-colours::%{_weapon}%::%{_hit}%::%loop-value-2%}, {_particle-scale::%loop-value-2%}) at {_draw} ~ {_arc::%loop-value-2%::%loop-value-1%}
			
			loop-value > 10:
				chance of 20%
				set {_v} to {_arc::2::%loop-value%}
				set {_ref} to {_arc::2::%loop-value%}
				add 90 to {_ref}'s pitch
				rotate {_v} around {_ref} by -45

				set {_rand} to random vector
				set {_rand}'s vector length to 0.5

				draw 0 of enchanted hit at {_draw} ~ {_arc::3::%loop-value%} with offset {_v}+{_rand} with extra 0.3

			
			# hitbox
			mod(loop-value, {_hitbox}) = 0:
				loop entities in radius 2.75 of ({_draw} ~ {_arc::2::%loop-value%}) where [input != {_p}]:
					isDamageableEntity(loop-entity, {_p}) = true
					{_hit::*} doesn't contain loop-entity

					hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon})
					make {_p} damage loop-entity by {_dmg}
					push loop-entity (vector from {_p} to loop-entity) at speed 0.5 * {_atk-scale}
					push loop-entity up at speed 0.35 * {_atk-scale}
					add loop-entity to {_hit::*}



			mod(loop-value,20) = 0
			wait 1 tick



	else if {_hit} = 3:
		set {_hit} to 1 # used for particles

		set {_dir} to 1
		set {_arc} to 90 # arc length
		set {_angle} to 45 + random number between -10 and 10
		set {_yaw} to {_p}'s yaw
		set {_pitch} to {_p}'s pitch
		set {_hitbox} to {_arc}/3

		set {_arc::1::*} to baseArc({_yaw}, {_pitch}, 3.2, {_dir}, {_arc}, 1, {_angle})
		set {_arc::2::*} to baseArc({_yaw}, {_pitch}, 3.5, {_dir}, {_arc}, 1, {_angle})
		set {_arc::3::*} to baseArc({_yaw}, {_pitch}, 3.8, {_dir}, {_arc}, 1, {_angle})

		play sound "entity.player.attack.sweep" at volume 3 at pitch 1.3+{_sound-scale} at {_p}
		play sound "item.trident.throw" at volume 3 at pitch 1.3+{_sound-scale} at {_p}
		play sound "sword.slash" at volume 3 at pitch 1.35+{_sound-scale} at {_p}

		set {_draw} to location of {_p}'s head
		loop {_arc} times:
			
			loop 3 times:
				draw 1 of dust using dustOption({-colours::%{_weapon}%::%{_hit}%::%loop-value-2%}, {_particle-scale::%loop-value-2%}) at {_draw} ~ {_arc::%loop-value-2%::%loop-value-1%}
			
			loop-value > 10:
				chance of 20%
				set {_v} to {_arc::2::%loop-value%}
				set {_ref} to {_arc::2::%loop-value%}
				add 90 to {_ref}'s pitch
				rotate {_v} around {_ref} by -45

				set {_rand} to random vector
				set {_rand}'s vector length to 0.5

				draw 0 of enchanted hit at {_draw} ~ {_arc::3::%loop-value%} with offset {_v}+{_rand} with extra 0.3

			
			# hitbox
			mod(loop-value, {_hitbox}) = 0:
				loop entities in radius 2.75 of ({_draw} ~ {_arc::2::%loop-value%}) where [input != {_p}]:
					isDamageableEntity(loop-entity, {_p}) = true
					{_hit::*} doesn't contain loop-entity

					hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon})
					make {_p} damage loop-entity by {_dmg}
					push loop-entity (vector from {_p} to loop-entity) at speed 0.5 * {_atk-scale}
					push loop-entity up at speed 0.35 * {_atk-scale}
					add loop-entity to {_hit::*}



			mod(loop-value,20) = 0
			wait 1 tick



	else if {_hit} = 4:
		set {_hit} to 1 # used for particles

		set {_dir} to -1
		set {_arc} to 90 # arc length
		set {_angle} to 45 + random number between -10 and 10
		set {_yaw} to {_p}'s yaw
		set {_pitch} to {_p}'s pitch
		set {_hitbox} to {_arc}/3

		set {_arc::1::*} to baseArc({_yaw}, {_pitch}, 3.2, {_dir}, {_arc}, 1, {_angle})
		set {_arc::2::*} to baseArc({_yaw}, {_pitch}, 3.5, {_dir}, {_arc}, 1, {_angle})
		set {_arc::3::*} to baseArc({_yaw}, {_pitch}, 3.8, {_dir}, {_arc}, 1, {_angle})

		play sound "entity.player.attack.sweep" at volume 3 at pitch 1+{_sound-scale} at {_p}
		play sound "item.trident.throw" at volume 3 at pitch 1.1+{_sound-scale} at {_p}
		play sound "sword.slash" at volume 3 at pitch 1+{_sound-scale} at {_p}

		set {_draw} to location of {_p}'s head
		loop {_arc} times:
			
			loop 3 times:
				draw 1 of dust using dustOption({-colours::%{_weapon}%::%{_hit}%::%loop-value-2%}, {_particle-scale::%loop-value-2%}) at {_draw} ~ {_arc::%loop-value-2%::%loop-value-1%}
			
			loop-value > 10:
				chance of 20%
				set {_v} to {_arc::2::%loop-value%}
				set {_ref} to {_arc::2::%loop-value%}
				add 90 to {_ref}'s pitch
				rotate {_v} around {_ref} by -45

				set {_rand} to random vector
				set {_rand}'s vector length to 0.5

				draw 0 of enchanted hit at {_draw} ~ {_arc::3::%loop-value%} with offset {_v}+{_rand} with extra 0.3

			
			# hitbox
			mod(loop-value, {_hitbox}) = 0:
				loop entities in radius 2.75 of ({_draw} ~ {_arc::2::%loop-value%}) where [input != {_p}]:
					isDamageableEntity(loop-entity, {_p}) = true
					{_hit::*} doesn't contain loop-entity

					hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon})
					make {_p} damage loop-entity by {_dmg}
					push loop-entity (vector from {_p} to loop-entity) at speed 0.5 * {_atk-scale}
					push loop-entity up at speed 0.35 * {_atk-scale}
					add loop-entity to {_hit::*}



			mod(loop-value,20) = 0
			wait 1 tick
	




	else:
		set {_hit} to 1 # used for particles

		set {_dir} to -1
		set {_arc} to 90 # arc length
		set {_angle} to 80 + random number between -10 and 10
		set {_yaw} to {_p}'s yaw
		set {_pitch} to {_p}'s pitch
		set {_hitbox} to {_arc}/3

		set {_arc::1::*} to baseArc({_yaw}, {_pitch}, 3.2, {_dir}, {_arc}, 1, {_angle})
		set {_arc::2::*} to baseArc({_yaw}, {_pitch}, 3.5, {_dir}, {_arc}, 1, {_angle})
		set {_arc::3::*} to baseArc({_yaw}, {_pitch}, 3.8, {_dir}, {_arc}, 1, {_angle})

		play sound "entity.player.attack.sweep" at volume 3 at pitch 0.9+{_sound-scale} at {_p}
		play sound "item.trident.throw" at volume 3 at pitch 1+{_sound-scale} at {_p}
		play sound "sword.slash" at volume 3 at pitch 0.85+{_sound-scale} at {_p}

		set {_draw} to location of {_p}'s head
		loop {_arc} times:
			
			loop 3 times:
				draw 1 of dust using dustOption({-colours::%{_weapon}%::%{_hit}%::%loop-value-2%}, {_particle-scale::%loop-value-2%}) at {_draw} ~ {_arc::%loop-value-2%::%loop-value-1%}
			
			loop-value > 10:
				chance of 20%
				set {_v} to {_arc::2::%loop-value%}
				set {_ref} to {_arc::2::%loop-value%}
				add 90 to {_ref}'s pitch
				rotate {_v} around {_ref} by -45

				set {_rand} to random vector
				set {_rand}'s vector length to 0.5

				draw 0 of enchanted hit at {_draw} ~ {_arc::3::%loop-value%} with offset {_v}+{_rand} with extra 0.3

			
			# hitbox
			mod(loop-value, {_hitbox}) = 0:
				loop entities in radius 2.75 of ({_draw} ~ {_arc::2::%loop-value%}) where [input != {_p}]:
					isDamageableEntity(loop-entity, {_p}) = true
					{_hit::*} doesn't contain loop-entity

					hitCombo({_p}, {_hit}, {_atk-scale}, {_weapon})
					make {_p} damage loop-entity by {_dmg}
					push loop-entity (vector from {_p} to loop-entity) at speed 0.5 * {_atk-scale}
					push loop-entity up at speed 0.35 * {_atk-scale}
					add loop-entity to {_hit::*}



			mod(loop-value,20) = 0
			wait 1 tick


	