


function sendResourcepack(p: player, type: text="main"):
	
	wait 5 ticks
	if {_type} = "main":
        
		set {_url} to "https://download.mc-packs.net/pack/6511fe06938d548f23d16b3356ec3ed9988b0ce9.zip"
		set {_hash} to "6511fe06938d548f23d16b3356ec3ed9988b0ce9"
		set {_uuid} to random uuid
		send resource pack from url {_url} with uuid {_uuid} with hash {_hash} to {_p}



command /resourcepack:
	trigger:
		sendResourcepack(player)
